### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by mikkilevon**

### CODE REVIEW

**Review by CptPicard — DISMISSED** [review]

**Review by evolaine — APPROVED** [review]
@mikkilevon Are you sure you don't want ownership of the Amplify folder?

**Comment by mikkilevon** [comment]
> @mikkilevon Are you sure you don't want ownership of the Amplify folder?
I'm not sure.. If I add myself to it then I'm actually reviewing everything that happens 😅

**Comment by romuaa** [comment]
I would actually like to be as a code owner for the .github workflow files also. Then again I would also be reviewing everything...

**Review by AdrianMiksa — APPROVED** [review]

**Review by romuaa — APPROVED** [review]

**Review by adamchabin — APPROVED** [review]

**Review by romuaa — CHANGES_REQUESTED** [review]
I think @CptPicard and @AdrianMiksa Should be also owners of the /src/ ?

**Review by romuaa — APPROVED** [review]

**Pull request merged**
